steps:
  # Get ONS Design System (templates required in build)
  - name: alpine:3.20
    entrypoint: sh
    args:
      - -c
      - |
        set -e
        apk add --no-cache wget unzip ca-certificates
        chmod +x ./get_design_system.sh
        ./get_design_system.sh
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-image'
    args: ['build', '-t',
           '${_REGION}-docker.pkg.dev/${_DEPLOY_PROJECT_ID}/${_ARTIFACT_REPO_NAME}/${_IMAGE_NAME}:${_IMAGE_TAG}',
           '.']

  # Docker Push
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-image'
    args: ['push',
           '${_REGION}-docker.pkg.dev/${_DEPLOY_PROJECT_ID}/${_ARTIFACT_REPO_NAME}/${_IMAGE_NAME}:${_IMAGE_TAG}']

# set build options
timeout: 600s
options:
  logging: CLOUD_LOGGING_ONLY